[Variables]
TotalGame=10

Gamecover1=edge.png
gamedir1="shell:AppsFolder\Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"
Background1=#@#Background\edge.jpg

Gamecover2=steam.png
Gamedir2=C:\Program Files (x86)\Steam\Steam.exe
Background2=#@#Background\steam.png

Gamecover3=netflix.png
Gamedir3=shell:AppsFolder\4DF9E0F8.Netflix_mcm4njqhnhss8!Netflix.App
Background3=#@#Background\Netflix.png

Gamecover4=wingware101.png
Gamedir4=C:\Program Files (x86)\Wing IDE 101 6.1\bin\wing-101.exe
Background4=#@#Background\wing.png

Gamecover5=kodi.png
Gamedir5=C:\Program Files\Kodi\kodi.exe
Background5=#@#Background\kodi.jpg

Gamecover6=word.png
Gamedir6=C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE
Background6=#@#Background\word.jpg

Gamecover7=photoshop.png
Gamedir7=C:\Program Files\Adobe\Adobe Photoshop CC 2019\Photoshop.exe
Background7=#@#Background\photoshop.jpg

Gamecover8=pc.png
Gamedir8=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Background8=#@#Background\pc.jpg

Gamecover9=setting.png
Gamedir9=ms-settings: 
Background9=#@#Background\setting.jpg

Gamecover10=youtube.png
Gamedir10=https://www.youtube.com/feed/subscriptions
Background10=#@#Background\youtube.jpg
